### ISSUE TITLE
How to interpret the output & visualize it

### ISSUE THREAD

**Issue by leonorrib** [amarinderthind/decontaminer#4]
Dear authors,

Thank you for developing this nice tool. I would like to know how to interpret the output files of decontaminer and whether there is an option of your tool that visualizes the output of it.

Best regards,
Leonor

**Comment by amarinderthind** [comment]
Thanks for reaching out ... the collecInfo.sh script yields some HTML pages which come with visualization. 

Alternatively one could also try the interactive server available here [Server](http://www-labgtp.na.icar.cnr.it/decontaminer/ ) seems Down at the moment. On this server, you can upload the result file to visualize, and also allow you to play interactively with some thresholds. 

Let me know if this helps, otherwise, I can share the R script.

**Comment by leonorrib** [comment]
Thank you for your answer. I'll try what you suggest.

Right, the server is still unavailable. It would be nice to be able to play with threasholds. Could you share the R script?

Best regards

**Comment by amarinderthind** [comment]
Sorry, Thanks for the reminder. I will update you today or tomorrow. it occupied

**Comment by amarinderthind** [comment]
Hi, @leonorrib I shared the code here https://rpubs.com/amarinder1/deontaminer (Click on the tab to show code; on the right-hand side) and also uploaded the R_decontaminer_visualizationScript 
 https://github.com/amarinderthind/decontaminer/tree/master/R_decontaminer_visualizationScript

**Comment by leonorrib** [comment]
Thank you :)
